version: '3.8'

services:
  frontend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"

volumes:
  milvus_data: